import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/store/Provider";
import Navbar from "@/componnets/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-900 antialiased`}
      >
        <Provider>
          <Navbar />
        {children}
        </Provider>
      </body>
    </html>
  );
}
